"""
Django settings for BioguardBackend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

AUTH model:
- Firebase handles signup/login/password rest on the Next.js frontend
- The frontend sends the Firebase ID token as `Authorization: Bearer <token>`
    on every API request.
- Django never stores passwords. 'accounts.authentication.FirebaseAuthentication'
  verifies the token sever-side and maps it to a local `Profie` row (in
  Supabase Postgres) that holds name, username, clinic membership, etc.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from decouple import Csv, config 

import firebase_admin
from firebase_admin import credentials

# This loads the variable from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize the Firebase Admin SDK exactly once per process.

# ----- Firebase Admin SDK ------
FIREBASE_TYPE = config("FIREBASE_TYPE")
FIREBASE_PROJECT_ID = config("FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY_ID = config("FIREBASE_PRIVATE_KEY_ID")
FIREBASE_PRIVATE_KEY = config("FIREBASE_PRIVATE_KEY")
FIREBASE_CLIENT_EMAIL = config("FIREBASE_CLIENT_EMAIL")
FIREBASE_CLIENT_ID = config("FIREBASE_CLIENT_ID")
FIREBASE_AUTH_URI = config("FIREBASE_AUTH_URI")
FIREBASE_TOKEN_URI = config("FIREBASE_TOKEN_URI")
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = config("FIREBASE_AUTH_PROVIDER_X509_CERT_URL")
FIREBASE_CLIENT_X509_CERT_URL = config("FIREBASE_CLIENT_X509_CERT_URL")
FIREBASE_UNIVERSE_DOMAIN = config("FIREBASE_UNIVERSE_DOMAIN")

if not firebase_admin._apps:
    # Build Firebase credentials from environment variables
    firebase_config = {
        "type": FIREBASE_TYPE,
        "project_id": FIREBASE_PROJECT_ID,
        "private_key_id": FIREBASE_PRIVATE_KEY_ID,
        "private_key": FIREBASE_PRIVATE_KEY,
        "client_email": FIREBASE_CLIENT_EMAIL,
        "client_id": FIREBASE_CLIENT_ID,
        "auth_uri": FIREBASE_AUTH_URI,
        "token_uri": FIREBASE_TOKEN_URI,
        "auth_provider_x509_cert_url": FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
        "client_x509_cert_url": FIREBASE_CLIENT_X509_CERT_URL,
        "universe_domain": FIREBASE_UNIVERSE_DOMAIN,
    }
    try:
        cred = credentials.Certificate(firebase_config)
        options = {
            'clockSkew' : 80, # Allow up to 60 seconds of skew
        }
        firebase_admin.initialize_app(cred, options)
    except Exception as e:
        print(f"Failed Firebase auth admin: {e}")

else:
    print("Nothing is happining ")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.dev", # This wildcard covers any ngrok domain
    ".ts.net" # Wildcard for tailscale nova laptop
    
]



# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BioguardBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BioguardBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get("POSTGRES_URL"),
        conn_max_age=600,
        conn_health_checks=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.FirebaseAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES" : [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES" : [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER" : "rest_framework.views.exception_handler",
}





# ----- CORS (your Next.js frontend) ------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://eduardos-macbook-pro-6.taildaaf33.ts.net", # Tailscale macbook pro address
    "https://eduardo-nova.taildaaf33.ts.net"
]
 
# Devtunnel and ngrok subdomains rotate, so match them with regexes instead
# of hardcoding the current (temporary) subdomain.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.use\.devtunnels\.ms$",
    r"^https://.*\.ngrok-free\.dev$",
    r"^https://.*\.ts\.net",
]
 
CORS_ALLOW_CREDENTIALS = True
 
 
# ----- CSRF Trusted Origins ------
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev",
    "https://*.use.devtunnels.ms",
    "http://eduardos-macbook-pro-6.taildaaf33.ts.net", # Tailscale macbook pro address
    "http://localhost:3000",
    "https://eduardo-nova.taildaaf33.ts.net"
]


#AUTH_PASSWORD_VALIDATORS = [] # unused: Django never handles password here
AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]


# --- For production Security hardening (only biting when DEBUG=False) --- 
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMIANS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")